import { useEffect, useState } from "react";
import { request } from "../api";
import { Card, ErrorBox, PageTitle, Table } from "../components/ui";

export function AcquisitionsPage({ token }) {
  const [suppliers, setSuppliers] = useState([]); const [books, setBooks] = useState([]); const [items, setItems] = useState([]); const [supplier, setSupplier] = useState({ name: "", phone: "" }); const [purchase, setPurchase] = useState({ supplier_id: "", book_title_id: "", quantity: "", unit_price: "", shelf_location: "", note: "" }); const [error, setError] = useState("");
  const load = async () => { const [supplierData, bookData, purchaseData] = await Promise.all([request("/acquisitions/suppliers", { token }), request("/catalog/books?include_inactive=true", { token }), request("/acquisitions", { token })]); setSuppliers(supplierData); setBooks(bookData); setItems(purchaseData); };
  useEffect(() => { load().catch((err) => setError(err.message)); }, [token]);
  async function addSupplier(event) { event.preventDefault(); try { await request("/acquisitions/suppliers", { token, method: "POST", body: supplier }); setSupplier({ name: "", phone: "" }); await load(); } catch (err) { setError(err.message); } }
  async function receive(event) { event.preventDefault(); try { await request("/acquisitions", { token, method: "POST", body: { supplier_id: Number(purchase.supplier_id), note: purchase.note || null, items: [{ book_title_id: Number(purchase.book_title_id), quantity: Number(purchase.quantity), unit_price: Number(purchase.unit_price), shelf_location: purchase.shelf_location || null }] } }); setPurchase({ supplier_id: "", book_title_id: "", quantity: "", unit_price: "", shelf_location: "", note: "" }); await load(); } catch (err) { setError(err.message); } }
  return <><PageTitle title="Nhập sách" description="Lập phiếu nhập sẽ tự tạo từng cuốn sách và mã vạch theo phiếu nếu không nhập mã riêng." /><ErrorBox message={error} /><div className="grid gap-6 xl:grid-cols-[1fr_22rem]"><div><Table><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4">Số phiếu</th><th className="p-4">Nhà cung cấp</th><th className="p-4">Ngày nhập</th><th className="p-4">Tổng tiền</th></tr></thead><tbody>{items.map((item) => <tr className="border-t" key={item.id}><td className="p-4">PN-{item.id}</td><td className="p-4">#{item.supplier_id}</td><td className="p-4">{new Date(item.received_at).toLocaleDateString("vi-VN")}</td><td className="p-4">{item.total_amount.toLocaleString("vi-VN")} đ</td></tr>)}{!items.length && <tr><td colSpan="4" className="p-8 text-center text-slate-500">Chưa có phiếu nhập.</td></tr>}</tbody></Table></div><div className="grid content-start gap-4"><Card><h2 className="font-semibold">Nhà cung cấp</h2><form onSubmit={addSupplier} className="mt-4 grid gap-3"><input placeholder="Tên nhà cung cấp" value={supplier.name} onChange={(event) => setSupplier({ ...supplier, name: event.target.value })} required /><input placeholder="Số điện thoại" value={supplier.phone} onChange={(event) => setSupplier({ ...supplier, phone: event.target.value })} /><button className="bg-slate-800 text-white">Thêm nhà cung cấp</button></form></Card><Card><h2 className="font-semibold">Lập phiếu nhập</h2><form onSubmit={receive} className="mt-4 grid gap-3"><select value={purchase.supplier_id} onChange={(event) => setPurchase({ ...purchase, supplier_id: event.target.value })} required><option value="">Nhà cung cấp</option>{suppliers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={purchase.book_title_id} onChange={(event) => setPurchase({ ...purchase, book_title_id: event.target.value })} required><option value="">Đầu sách</option>{books.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><input type="number" min="1" placeholder="Số lượng" value={purchase.quantity} onChange={(event) => setPurchase({ ...purchase, quantity: event.target.value })} required /><input type="number" min="0" placeholder="Đơn giá" value={purchase.unit_price} onChange={(event) => setPurchase({ ...purchase, unit_price: event.target.value })} required /><input placeholder="Vị trí kệ" value={purchase.shelf_location} onChange={(event) => setPurchase({ ...purchase, shelf_location: event.target.value })} /><input placeholder="Ghi chú" value={purchase.note} onChange={(event) => setPurchase({ ...purchase, note: event.target.value })} /><button className="bg-indigo-600 text-white">Nhập sách</button></form></Card></div></div></>;
}
