import { useEffect, useState } from "react";
import { request } from "../api";
import { Card, ErrorBox, PageTitle, Table } from "../components/ui";

const roleLabels = { admin: "Quản trị", librarian: "Thủ thư", reader: "Bạn đọc" };

export function AdminPage({ token }) {
  const [users, setUsers] = useState([]); const [settings, setSettings] = useState([]); const [form, setForm] = useState({ full_name: "", email: "", password: "", role: "librarian" }); const [error, setError] = useState(""); const [saved, setSaved] = useState("");
  const load = async () => { const [userData, settingData] = await Promise.all([request("/users", { token }), request("/settings", { token })]); setUsers(userData); setSettings(settingData); };
  useEffect(() => { load().catch((err) => setError(err.message)); }, [token]);
  async function addUser(event) { event.preventDefault(); try { await request("/users", { token, method: "POST", body: form }); setForm({ full_name: "", email: "", password: "", role: "librarian" }); await load(); } catch (err) { setError(err.message); } }
  async function saveSetting(item) { try { await request(`/settings/${item.key}`, { token, method: "PUT", body: { value: item.value, description: item.description } }); setSaved(`Đã lưu ${item.key}`); } catch (err) { setError(err.message); } }
  return <><PageTitle title="Quản trị hệ thống" description="Tài khoản vận hành và quy định mượn/trả được kiểm soát tại đây." /><ErrorBox message={error} />{saved && <p className="mb-4 text-sm text-emerald-700">{saved}</p>}<div className="grid gap-6 xl:grid-cols-2"><Card><h2 className="font-semibold">Người dùng hệ thống</h2><Table><thead className="bg-slate-50 text-slate-500"><tr><th className="p-3">Họ tên</th><th className="p-3">Email</th><th className="p-3">Vai trò</th></tr></thead><tbody>{users.map((item) => <tr className="border-t" key={item.id}><td className="p-3">{item.full_name}</td><td className="p-3">{item.email}</td><td className="p-3">{roleLabels[item.role] ?? item.role}</td></tr>)}</tbody></Table><form onSubmit={addUser} className="mt-4 grid gap-3 sm:grid-cols-2"><input placeholder="Họ tên" value={form.full_name} onChange={(event) => setForm({ ...form, full_name: event.target.value })} required /><input type="email" placeholder="Email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} required /><input type="password" minLength="6" placeholder="Mật khẩu" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} required /><select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}><option value="librarian">Thủ thư</option><option value="admin">Quản trị viên</option></select><button className="bg-indigo-600 text-white sm:col-span-2">Tạo người dùng nội bộ</button></form></Card><Card><h2 className="font-semibold">Quy định thư viện</h2><div className="mt-4 grid gap-3">{settings.map((item) => <div key={item.key} className="grid gap-2 rounded-lg border border-slate-200 p-3 sm:grid-cols-[1fr_6rem_auto]"><label className="text-sm"><b>{item.key}</b><span className="mt-1 block text-slate-500">{item.description}</span></label><input value={item.value} onChange={(event) => setSettings(settings.map((entry) => entry.key === item.key ? { ...entry, value: event.target.value } : entry))} /><button onClick={() => saveSetting(item)} className="border border-slate-300 text-sm hover:bg-slate-50">Lưu</button></div>)}</div></Card></div></>;
}
