import { useEffect, useMemo, useState } from "react";
import { request } from "../api";
import { Card, ErrorBox, PageTitle, Table } from "../components/ui";

const initialBook = { title: "", isbn: "", category_id: "", publisher_id: "", author_ids: [], language: "Tiếng Việt", publication_year: "" };

export function CatalogPage({ token }) {
  const [books, setBooks] = useState([]); const [lookups, setLookups] = useState({ categories: [], authors: [], publishers: [] });
  const [book, setBook] = useState(initialBook); const [copy, setCopy] = useState({ book_id: "", barcode: "", shelf_location: "" });
  const [lookupName, setLookupName] = useState(""); const [lookupType, setLookupType] = useState("categories"); const [search, setSearch] = useState(""); const [error, setError] = useState("");
  const load = async () => { const [bookData, categories, authors, publishers] = await Promise.all([request(`/catalog/books${search ? `?search=${encodeURIComponent(search)}` : ""}`, { token }), request("/catalog/categories", { token }), request("/catalog/authors", { token }), request("/catalog/publishers", { token })]); setBooks(bookData); setLookups({ categories, authors, publishers }); };
  useEffect(() => { load().catch((err) => setError(err.message)); }, [token]);
  const available = useMemo(() => books.reduce((sum, item) => sum + item.copies.filter((entry) => entry.status === "available").length, 0), [books]);
  async function createBook(event) { event.preventDefault(); setError(""); try { await request("/catalog/books", { token, method: "POST", body: { ...book, category_id: Number(book.category_id), publisher_id: book.publisher_id ? Number(book.publisher_id) : null, publication_year: book.publication_year ? Number(book.publication_year) : null, author_ids: book.author_ids.map(Number), isbn: book.isbn || null } }); setBook(initialBook); await load(); } catch (err) { setError(err.message); } }
  async function createLookup(event) { event.preventDefault(); try { await request(`/catalog/${lookupType}`, { token, method: "POST", body: { name: lookupName } }); setLookupName(""); await load(); } catch (err) { setError(err.message); } }
  async function addCopy(event) { event.preventDefault(); try { await request(`/catalog/books/${copy.book_id}/copies`, { token, method: "POST", body: { barcode: copy.barcode, shelf_location: copy.shelf_location || null } }); setCopy({ book_id: "", barcode: "", shelf_location: "" }); await load(); } catch (err) { setError(err.message); } }
  return <><PageTitle title="Sách và kho" description={`${books.length} đầu sách hiển thị · ${available} cuốn đang sẵn có`} /><ErrorBox message={error} />
    <div className="grid gap-6 xl:grid-cols-[1fr_21rem]"><div><div className="mb-3 flex gap-2"><input className="w-full" placeholder="Tìm theo tên, ISBN hoặc tác giả" value={search} onChange={(event) => setSearch(event.target.value)} /><button className="bg-slate-800 text-white" onClick={() => load().catch((err) => setError(err.message))}>Tìm</button></div>
      <Table><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4">Đầu sách</th><th className="p-4">Thể loại / tác giả</th><th className="p-4">Kho</th><th className="p-4">Vị trí</th></tr></thead><tbody>{books.map((item) => <tr key={item.id} className="border-t"><td className="p-4 font-medium">{item.title}<div className="text-xs font-normal text-slate-500">{item.isbn || "Không có ISBN"} · {item.publication_year || "—"}</div></td><td className="p-4">{item.category.name}<div className="text-xs text-slate-500">{item.authors.map((author) => author.name).join(", ") || "Chưa có tác giả"}</div></td><td className="p-4">{item.copies.filter((entry) => entry.status === "available").length}/{item.copies.length} sẵn có</td><td className="p-4 text-xs text-slate-500">{item.copies.map((entry) => entry.shelf_location).filter(Boolean).join(", ") || "—"}</td></tr>)}{!books.length && <tr><td colSpan="4" className="p-8 text-center text-slate-500">Chưa có đầu sách.</td></tr>}</tbody></Table></div>
      <div className="grid content-start gap-4"><Card><h2 className="font-semibold">Thêm đầu sách</h2><form onSubmit={createBook} className="mt-4 grid gap-3"><input placeholder="Tên sách" value={book.title} onChange={(event) => setBook({ ...book, title: event.target.value })} required /><input placeholder="ISBN" value={book.isbn} onChange={(event) => setBook({ ...book, isbn: event.target.value })} /><select value={book.category_id} onChange={(event) => setBook({ ...book, category_id: event.target.value })} required><option value="">Chọn thể loại</option>{lookups.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={book.publisher_id} onChange={(event) => setBook({ ...book, publisher_id: event.target.value })}><option value="">Chọn nhà xuất bản</option>{lookups.publishers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select multiple className="h-20" value={book.author_ids} onChange={(event) => setBook({ ...book, author_ids: Array.from(event.target.selectedOptions, (option) => option.value) })}>{lookups.authors.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input type="number" placeholder="Năm xuất bản" value={book.publication_year} onChange={(event) => setBook({ ...book, publication_year: event.target.value })} /><button className="bg-indigo-600 text-white">Lưu đầu sách</button></form></Card>
        <Card><h2 className="font-semibold">Thêm cuốn sách</h2><form onSubmit={addCopy} className="mt-4 grid gap-3"><select value={copy.book_id} onChange={(event) => setCopy({ ...copy, book_id: event.target.value })} required><option value="">Chọn đầu sách</option>{books.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><input placeholder="Mã vạch" value={copy.barcode} onChange={(event) => setCopy({ ...copy, barcode: event.target.value })} required /><input placeholder="Vị trí kệ" value={copy.shelf_location} onChange={(event) => setCopy({ ...copy, shelf_location: event.target.value })} /><button className="bg-emerald-600 text-white">Thêm cuốn</button></form></Card>
        <Card><h2 className="font-semibold">Khai báo danh mục</h2><form onSubmit={createLookup} className="mt-4 grid gap-3"><select value={lookupType} onChange={(event) => setLookupType(event.target.value)}><option value="categories">Thể loại</option><option value="authors">Tác giả</option><option value="publishers">Nhà xuất bản</option></select><input placeholder="Tên mới" value={lookupName} onChange={(event) => setLookupName(event.target.value)} required /><button className="bg-slate-800 text-white">Thêm danh mục</button></form></Card></div>
    </div></>;
}
