import { useEffect, useState } from "react";
import { request } from "../api";
import { Card, ErrorBox, PageTitle, Table } from "../components/ui";

export function ReportsPage({ token }) {
  const [overdue, setOverdue] = useState([]); const [popular, setPopular] = useState([]); const [categories, setCategories] = useState([]); const [error, setError] = useState("");
  useEffect(() => { Promise.all([request("/reports/overdue", { token }), request("/reports/popular-books", { token }), request("/reports/borrow-by-category", { token })]).then(([overdueItems, popularBooks, categoryData]) => { setOverdue(overdueItems); setPopular(popularBooks); setCategories(categoryData); }).catch((err) => setError(err.message)); }, [token]);
  return <><PageTitle title="Báo cáo và thống kê" description="Báo cáo được tổng hợp trực tiếp từ lịch sử mượn/trả, không lưu dữ liệu báo cáo trùng lặp." /><ErrorBox message={error} /><div className="grid gap-6 xl:grid-cols-2"><Card><h2 className="font-semibold">Sách trả trễ</h2><Table><thead className="bg-slate-50 text-slate-500"><tr><th className="p-3">Bạn đọc</th><th className="p-3">Sách</th><th className="p-3">Quá hạn</th></tr></thead><tbody>{overdue.map((item) => <tr className="border-t" key={`${item.loan_id}-${item.barcode}`}><td className="p-3">{item.reader_name}<div className="text-xs text-slate-500">{item.card_number}</div></td><td className="p-3">{item.title}<div className="text-xs text-slate-500">{item.barcode}</div></td><td className="p-3 font-semibold text-rose-600">{item.overdue_days} ngày</td></tr>)}{!overdue.length && <tr><td colSpan="3" className="p-5 text-center text-slate-500">Không có sách quá hạn.</td></tr>}</tbody></Table></Card><Card><h2 className="font-semibold">Sách được mượn nhiều</h2><ol className="mt-3 divide-y">{popular.map((item, index) => <li className="flex items-center justify-between py-3" key={item.book_title_id}><span><b className="mr-3 text-indigo-600">#{index + 1}</b>{item.title}</span><span className="text-sm text-slate-500">{item.borrow_count} lượt</span></li>)}{!popular.length && <li className="py-5 text-center text-slate-500">Chưa có dữ liệu mượn.</li>}</ol></Card><Card><h2 className="font-semibold">Lượt mượn theo thể loại</h2><div className="mt-4 grid gap-2">{categories.map((item) => <div key={item.category} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2"><span>{item.category}</span><b>{item.borrow_count}</b></div>)}{!categories.length && <p className="text-slate-500">Chưa có dữ liệu.</p>}</div></Card></div></>;
}
